name: flutter_audio_games
version: 0.51.0
description: A package which makes it easy to write audio games in Flutter.
homepage: https://github.com/chrisnorman7/flutter_audio_games
environment:
  sdk: ^3.10.2
  flutter: ">=1.17.0"

dependencies:
  backstreets_widgets: ^0.40.0
  flutter:
    sdk: flutter
  flutter_soloud: ^3.4.6
  http: ^1.5.0
  logging: ^1.3.0
  path: ^1.9.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
